quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgre_suri}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/Suri_firuvet}

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false

quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH,HEAD
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,origin
quarkus.http.cors.exposed-headers=location,info
quarkus.http.cors.access-control-max-age=86400

rabbitmq-host=${RABBITMQ_HOST:localhost}
rabbitmq-port=${RABBITMQ_PORT:5672}
rabbitmq-username=${RABBITMQ_USERNAME:guest}
rabbitmq-password=${RABBITMQ_PASSWORD:guest}
rabbitmq-virtual-host=${RABBITMQ_VIRTUAL_HOST:/}

# Auditoria -> RabbitMQ
mp.messaging.outgoing.auditoria-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.auditoria-out.exchange.name=suri.auditoria
mp.messaging.outgoing.auditoria-out.exchange.type=direct
mp.messaging.outgoing.auditoria-out.exchange.declare=true
mp.messaging.outgoing.auditoria-out.default-routing-key=auditoria.movimiento

# RabbitMQ -> Auditoria
mp.messaging.incoming.auditoria-in.connector=smallrye-rabbitmq
mp.messaging.incoming.auditoria-in.queue.name=suri.auditoria.movimientos
mp.messaging.incoming.auditoria-in.queue.declare=true
mp.messaging.incoming.auditoria-in.exchange.name=suri.auditoria
mp.messaging.incoming.auditoria-in.exchange.type=direct
mp.messaging.incoming.auditoria-in.routing-keys=auditoria.movimiento
mp.messaging.incoming.auditoria-in.failure-strategy=reject